# Generated by Django 4.1.2 on 2022-11-02 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCat', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=25)),
                ('prix', models.FloatField()),
                ('qte', models.IntegerField()),
                ('dateAjout', models.DateField()),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasin.categorie')),
            ],
        ),
    ]
